const positions = [
  'top-left',
  'top-center',
  'top-right',
  'bottom-left',
  'bottom-center',
  'bottom-right',
];

const notificationtype =[
  'notification',
  'modal',
  'alert'
]

const modaltype = [
  'modal-no-action',
  'modal-accept',
  'modal-accept-reject'
];


export interface notificationmsg {
  id: string,                //Auto generated by store : All
  text: string,              //Notification & Modal  
  notificationtype: string,  // All
  modaltype?:string,         // Modal
  comp?:any,                 // Modal
  position?:string,          // Notification
  type:string,               // Notification
  withoutStyles?:Boolean,    // Notification - Not sure of the function
  removeAfter?:number,       // Notification - TODO disable for modal?
  disableClose?:Boolean,     // Modal - TODO
  width?:string;             // Modal - TODO
  height?:string;            // Modal - TODO
  returnData?:any            // Modal - TODO to return value on close
}

// TODO emitting value from Modal on Close

export  { positions, notificationtype, modaltype };
