const positions = [
  'top-left',
  'top-center',
  'top-right',
  'bottom-left',
  'bottom-center',
  'bottom-right',
];

const notificationtype =[
  'notification',
  'modal',
  'alert'
]

const modaltype = [
  'modal-no-action',
  'modal-accept',
  'modal-accept-reject',
  'modal-loading'
];

/* Return data for different modal types
 * modal-accept-reject -> {accept:false} {accept:true} 
 *                        {closed:true} on diableclose==true and closed by esc or click outside form
 * modal-accept        -> {accept:true}
 * modal-no-action     -> {closed:true}
 * */

export interface notificationmsg {
  id: string,                //Auto generated by store : All
  targetid: string,          // Only for Alert
  title: string              //Notification & Modal   
  text: string,              //All  
  notificationtype: string,  // All
  modaltype?:string,         // Modal
  comp?:any,                 // Modal
  position?:string,          // Notification
  type:string,               // Notification & Alert (success | warning | error | info)
  withoutStyles?:Boolean,    // Notification - Not sure of the function
  removeAfter?:number,       // Notification - TODO disable for modal?  
  width?:string;             // Modal - TODO
  height?:string;            // Modal - TODO
  returnData?:any            // Modal - Returns data to user via a promise.
  disableClose?: boolean      //Modal = for backdrop, others it is to give close buton - TRUE by default
  hasbackdrop?:boolean        // Modal - TRUE by default
  singleton?:boolean          // Alert - TRUE by default
}

// TODO emitting value from Modal on Close

export  { positions, notificationtype, modaltype };
